### PR TITLE
Feature/369 code reorganization gf

### PR DESCRIPTION
**Pull request by ravewebdev**
References #369

### Description

Updates GF handling to work with WP GraphQL Gravity Forms v0.4.
Refactors GF form submission to use WP GraphQL instead of REST API.
**Removes** support for FileUploadField as media uploads are currently not supported by WP GraphQL and WP GraphQL Gravity Forms. :disappointed: (New issue to re-add once uploads are supported: #380)

**Note: This PR requires the [BE PR](https://github.com/WebDevStudios/wds-headless-wordpress/pull/22) to be merged first.**

### Verification

https://nextjs-wordpress-starter-7ibw9etl3-webdevstudios.vercel.app/contact
1. Fill out and submit form.
2. Form should display success message.
3. Go to admin and confirm entry displays as expected.

### CODE REVIEW

**Comment by jrfoell** [comment]
Do we want to remove file upload support? I know we had specifically worked around the GraphQL because it didn't support media uploads. Wondering if we should keep that piece in place until we have a working alternative.

**Comment by jrfoell** [comment]
I got this branch up and running and got this error when dealing with the checkbox field:

```Variable "$fieldValues" got invalid value [{"id":6,"value":["Linux"]}]; Expected type String at value[0].value; String cannot represent a non string value: ["Linux"]```

I tried both numeric and string values for the checkboxes, but both yielded the same error - looks like they're coming in as array values since you can select multiple.

**Comment by ravewebdev** [comment]
> Do we want to remove file upload support? I know we had specifically worked around the GraphQL because it didn't support media uploads. Wondering if we should keep that piece in place until we have a working alternative.

We can hold off if media uploads are a hard requirement, but the drive behind this was to bring all the WP integrations in-line and avoid the `getWPUrl.js` workaround. If we do hold off on this, I'll need to break some of this PR off into a new one so we can get the WP GraphQL Gravity Forms v0.4+ fixes in.

> I got this branch up and running and got this error when submitting a form with a checkbox field:
> 
> `Variable "$fieldValues" got invalid value [{"id":6,"value":["Linux"]}]; Expected type String at value[0].value; String cannot represent a non string value: ["Linux"]`
> 
> I tried both numeric and string values for the checkboxes, but both yielded the same error - looks like they're coming in as array values since you can select multiple.

I'll look into this on my local.

**Comment by ravewebdev** [comment]
> I got this branch up and running and got this error when submitting a form with a checkbox field:
> 
> `Variable "$fieldValues" got invalid value [{"id":6,"value":["Linux"]}]; Expected type String at value[0].value; String cannot represent a non string value: ["Linux"]`
> 
> I tried both numeric and string values for the checkboxes, but both yielded the same error - looks like they're coming in as array values since you can select multiple.

I fixed the issue here and a few other related bugs I came across. Form submission should be working now.

**Comment by gregrickaby** [comment]
@ravewebdev @jrfoell I'm good with this PR because it's part of a larger re-organization effort.

However, media uploads/attachments are required _per the original specifications of this starter_. Furthermore, uploads/attachments will be needed for an upcoming project. After the code refactoring and cleanups are merged in, work on #380 needs to start on immediately.

**Review by gregrickaby — CHANGES_REQUESTED** [review]
@ravewebdev There's a merge conflict. Can you fix it up? Thanks!

**Review by gregrickaby — APPROVED** [review]

**Pull request merged**
