### PR TITLE
Fix hierarchical page previews

### PR DESCRIPTION
**Pull request by koraysels**
complements [this PR](https://github.com/WebDevStudios/wds-headless-core/pull/3) in the wds-headless-core plugin 

Fixes preview redirects for hierarchical pages.

### CODE REVIEW

**Comment by koraysels** [comment]
dont we want this ?

**Comment by ravewebdev** [comment]
@koraysels in my tests, this change actually breaks previews. Can you test with the latest versions of this repo and the `wds-headless-*` plugins and confirm whether you're still seeing errors with previews?

**Comment by koraysels** [comment]
the problem is that if you create a a hierarchical page. the code for creating the permalink simply does not include the parent page in the slug. which is what i fixed with a very simple solution.  it is related to the pr i made in the core plugin.
so you need to pull in both changes for this to work 

https://github.com/WebDevStudios/wds-headless-core/pull/3/files

**Comment by ravewebdev** [comment]
@koraysels as I mentioned, this PR actually broke previews on my install. I did some digging and created a [new PR](https://github.com/WebDevStudios/nextjs-wordpress-starter/pull/827) that seems to work in all cases on my end, can you please test and let me know if the issue is resolved on your install?

**Comment by koraysels** [comment]
I will, but in my tests the opposite is true.. I reverted to using my fork. Will test later next week;) thanks 

Sorry for being brief, sent from my iPhone

**Pull request closed without merging**
